conventional-changelog/validate-commit-msg

- index.js
Love that you have this pattern in here, I was just about to add it.
I find myself frequently using `WIP` for placeholders. I almost never include the colon. 
When typing a quick `WIP` commit message, it's easier / faster to omit the colon. I think it makes sense to be less stringent on the ignore use case.
Thoughts?
> fix(WIP): Remove `:` from WIP

- package.json
Without a version entry in package.json a npm install via git URL fails
```
npm i https://github.com/kentcdodds/validate-commit-msg.git
npm ERR! addLocal Could not install [...]
npm ERR! No version provided in package.json
```
> fix(package): add version to package.json

- index.js
- index.test.js
should protect when called without an actual message
> fix(robustness): handle undefined message buffer, closes #9

- index.js
- index.test.js
- package.json
In this PR the `IGNORED` regular expression is updated to skip commits that contain just a valid semver as the ones generated by `npm version`.
Closes #13
> feat(validateMessage): Allow semver commits

- index.js
- index.test.js
- package.json
Really helpfull to not have to rewrite everything. It happened to me because I went over the 100 chars limit... :-)
It will change this output :
```
INVALID COMMIT MSG: is longer than 100 characters !
```
to :
```
INVALID COMMIT MSG: is longer than 100 characters !
feat(superCoolScopeDesignedToBeSpeciallyLong): talk about this super cool feature, but talking about it too much making it exceed the length limit
```
> feat(validateMessage): display original message when it is not valid

- index.js
- index.test.js
This PR makes the commit message matching regular expression pattern more true to the spec by:                                                                    
* removing `fixup! ` as an allowed message prefix
* allowing any character except `)` and white space as scope name
* require a commit message subject
* removing unused pattern matching groups
**Before:**
**After:**
Signed-off-by: Hans Kristian Flaatten <hans@starefossen.com>
> Make commit matching pattern more true to the spec

- index.js
- index.test.js
`fixup!` and `squash!` are part of Git, commits tagged with them are not intended to be merged :
- http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html
- https://git-scm.com/docs/git-commit
```
$ (dev) git commit -m "Feature A is done"
[dev fb2f677] Feature A is done
$ (dev) git commit -m "Feature B is done"
[dev 733e2ff] Feature B is done
$ (dev) git commit --fixup fb2f677
[dev c5069d5] fixup! Feature A is done
```
```
$ (dev) git log --oneline
c5069d5 fixup! Feature A is done
733e2ff Feature B is done
fb2f677 Feature A is done
ac5db87 Previous commit
```
```
$ (dev) git rebase -i --autosquash ac5db87
ff4de2a Feature B is done
5478cee Feature A is done
ac5db87 Previous commit
```
If we do not want to allow fixup/squash (this is not in the Angular commit …
> feat: allow fixup! and squash!

- README.md
- index.js
- index.test.js
- package.json
If provided, the helpMessage string is displayed when a commit message is not valid. This allows
projects to provide a better developer experience for new contributors.
> feat(config): add helpMessage config option

- README.md
- index.js
- index.test.js
This change supports using `%s` in the config.helpMessage, and if the %s is included, then the default message isn't printed since it'll be put into the output of the help message.
> feat: support %s interpolate in helpMessage

- index.js
- index.test.js
Empty commits should abort the commit, but the validation still fails:
This change strips comments from the commit before verification and then if the message is actually empty, it'll abort the commit (with the same default git message):
> Support empty commits

- index.js
- index.test.js
Add capability for #32. This will avoid people from lose their long commit message on failures when using the `%s` placeholder.
> feat(helpMessage): print the entire message when using the %s placeholder

- index.js
- index.test.js
The merge message check is too strict. It fails auto merge commit messages because they don't
include the word into
> fix(lib): Reduced merge check strictness

- index.js
- index.test.js
From the git source [1] we can see that the only part that git generates for sure in the merge commit message is the
prefix `Merge `. This commit reduces the strictness of the merge detection to only that. While this might allow false
postives, I consider these better than false negatives (where committing is disallowed and people have to use
`--no-verify`).
[1]: https://github.com/git/git/blob/master/builtin/fmt-merge-msg.c#L418
> fix(lib): make merge commit regex even less strict (fix #35)

- index.js
- index.test.js
I'm always forgetting the list of custom types or the exact wording of the type, so here's a little something to show them if you got the type wrong.
```
13:12 jzetlen@work $ g acm "doc: whoops, forgot the 's' on 'docs'"
INVALID COMMIT MSG: "doc" is not allowed type ! Valid types are: feat, fix, docs, style, refactor, perf, test, chore, revert, tech
doc: whoops, forgot the 's' on 'docs'
```
> feat(helpMessage): show valid types when invalid type was used

- package.json
Only `index.js` is necessary at runtime; the installed package is already small, but what the hey :)
> chore: reduce tarball size

- index.js
- package.json
This PR fixes #43 
I had issues testing this code change because the config types were passed in from the _package.json_ so it was not getting to _commit-types_ from the module. 
A solution I thought was deleting the _types_ field from the _package.json_. Another was cloning the _package.json_, deleting the _types_ field and replace it after. Felt like too much effort, not sure it was worth it.
Suggestions are welcome on how to test it, if it's worth it.
> refactor(index): fetch commit-types from module

- index.js
I'm currently getting this thrown when I try and commit anything to my modules:
```
/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/validate-commit-msg/index.js:87
if (types !== '*' && types.indexOf(type) === -1) {
^
TypeError: types.indexOf is not a function
at validateMessage (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/validate-commit-msg/index.js:87:32)
at /Users/mattlewis/Code/open-source/angular2-calendar/node_modules/validate-commit-msg/index.js:149:10
```
This should do the trick, happy to follow up with a test, just wanted to get something out the door as I'm currently unable to commit to any of my modules 😄
> fix: use default commit types

- README.md
As someone who wasn't familiar with how husky worked, I had to dig through the docs a little bit to figure out that "commit-msg" wasn't a valid script. I figured it would be much better to be completely explicit about how to set it up, so people can just copy-and-paste for the recommended setup.
> docs(README): Clarify usage with husky

- index.js
- lib/cli.js
- package.json
- wallaby.config.js
This separation will facilitate further refactoring, moving the main validation to lib, split in
multiple files etc.
> refactor(cli-validation): separate cli behaviour from validation

- lib/validateMessage.js
- test/validateMessage.test.js
When `validate: true`, it should allow the user provided no scope. Commit message such as `chore: Publish` should pass.
However, the current setup tries to call multiple method on `undefined` in that situation. So I fixed that by adding `scope.length > 0` before validate any individual message.
> fix(scope): Allow no scope in the commit message when validate is set to true.

- lib/cli.js
Analysis: [cli.js](https://github.com/kentcdodds/validate-commit-msg/blob/master/lib/cli.js) is looking for the commit message from `git/COMMIT_EDITMSG` file irrespective of mode of committing the code (GIT BASH or GIT GUI or GITHUB)
GIT GUI will be storing the commit message in `.git/GITGUI_EDITMSG` file and we are [reading](https://github.com/kentcdodds/validate-commit-msg/blob/master/lib/cli.js#L47) from  `COMMIT_EDITMSG` file always for the commit message which is causing the issue.
Solution: Checking for the existance of `GITGUI_EDITMSG` file, if it is there then we are taking the commit message from that file else we are reading the message from `COMMIT_EDITMSG`. As `GITGUI_EDITMSG` will be created and deleted only when we are commiting from GIT GUI.
> Commit message not throwing error while commit from git gui

- README.md
The README did not reflect that `.vcmrc` must be valid JSON parse. Copy-pasing the default config from the README would cause a (silently suppressed) JSON parse error.
Solves #89
> docs: `.vcmrc` file must be valid JSON

- README.md
Replace `'` with `"` in the JSON config.
> docs: fix quotation marks in JSON file

- test/validateMessage.test.js
Coverage to test the scenario in #97 to verify it works and will continue to work internally just in case.
> test: Add coverage for template tags in message

- package.json
Fix the URLs in `package.json` to point directly to the new org repo.
> chore: Update package URLs to new org

- lib/cli.js
- test/cli.test.js
I've noticed that with #92 (released with `2.13.0`) we introduced a bug where the CLI dosn't exit the process correctly anymore. This was due to wrapping `validate()` in a try/catch statement although neither `validate()` or `validateMessage()` actually throws.
To reproduce:
- Install `validate-commit-msg` v2.13.0
- attempt to commit locally with a non-valid msg
=> You'll see the error message on the CLI, but the commit will still happen anyway (check git log)
> Fix validate exit
